version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: archon
      POSTGRES_USER: archon
      POSTGRES_PASSWORD: archon
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  backend:
    build: .
    depends_on:
      - db
      - redis
      - qdrant
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://archon:archon@db:5432/archon

  mock-archon:
    build:
      context: ./mock-archon
    ports:
      - "8054:8054"
      - "8282:8054"
    environment:
      - PORT=8054

volumes:
  pgdata:
  qdrant_data:
