name: MCP contract
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Docker Compose
        run: |
          python -m pip install --upgrade pip
          pip install docker-compose
      - name: Install test deps
        run: |
          pip install -r requirements-dev.txt
      - name: Run contract test
        run: |
          docker compose -f docker-compose.mock.yml up --build -d
          pytest -q tests/test_mcp_contract.py::test_mcp_contract
          docker compose -f docker-compose.mock.yml down --volumes
